name: Publish Fulcrum-YTN Windows Release

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set WORKER_COUNT env
        run: echo "WORKER_COUNT=$(nproc)" >> $GITHUB_ENV

      - name: Set TAG_NAME env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Build static Windows executable
        run: |
          chmod +x contrib/build/build.sh
          GIT_REPO=$(pwd) contrib/build/build.sh windows master

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fulcrum-windows-static
          path: dist/win/
